name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: newbornhealthapi  # set this to the name of your Azure Web App
  PYTHON_VERSION: '3.11'              # set this to the Python version to use

on:
  push:
    paths:
      - "newborn-health-api/api/**"
    branches:
      - main  # Adjust if needed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies (Exclude pywin32 on Linux)
        run: |
          sed -i '/pywin32/d' newborn-health-api/api/requirements.txt
          pip install -r newborn-health-api/api/requirements.txt
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .
          
      - name: Zip the API folder
        run: zip -r deployment.zip newborn-health-api/api
        
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deployment.zip  # Specify the zipped file for deployment