name: Deploy Flask API with Key Vault

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Allow OIDC authentication
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Retrieve Secrets from Azure Key Vault
      run: |
        API_KEY=$(az keyvault secret show --name API_KEY --vault-name ${{ secrets.KEY_VAULT_NAME }} --query value -o tsv)

        echo "API_KEY=${API_KEY}" >> .env

    - name: Verify .env File (Optional)
      run: cat .env  # Remove in production

    - name: Deploy Flask API to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        package: .
        slot-name: production
